# Stubs for example.subpackage.submodule (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SampleClass: Any
answer: int

def add(*args, **kwargs): ...
