# Stubs for example.subpackage (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

submodule: Any
where: str

def concat(*args, **kwargs): ...
